[omnipbx.csv]
format = dsv
separator_character = ,
quote_character = "
quote_escape_character = "
quoting_method = all
fields = start,uniqueid(noquote),omni_linkedid(uservar^noquote),src,dst,clid,channel,dstchannel,lastapp,lastdata,duration,billsec,disposition,amaflags,recordingfile(uservar),direction(uservar),trunk_name(uservar),route_name(uservar),queue_name(uservar),ivr_name(uservar),caller_extension(uservar),callee_extension(uservar)
