[globals]
OMNIPBX_CONTEXT=omnipbx-internal

[omnipbx-internal]
include => from-internal-trunks
include => from-internal-ring-groups
include => from-internal-queues
include => from-internal-ivrs
exten => i,1,Hangup()
same => n,Hangup()

#include generated/extensions.generated.conf
#include generated/extensions.trunks.generated.conf
#include generated/ring_groups.generated.conf
#include generated/queues_dialplan.generated.conf
#include generated/ivrs.generated.conf
#include generated/inbound_routes.generated.conf
