[general]
enabled = yes
port = 5038
bindaddr = 127.0.0.1

[omnipbx]
secret = change-me
deny = 0.0.0.0/0.0.0.0
permit = 127.0.0.1/255.255.255.255
read = system,call,log,verbose,command,agent,user,config
write = system,call,command,agent,user,config,originate
