[global]
type = global
user_agent = OmniPBX

[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060

[transport-wss]
type = transport
protocol = wss
bind = 0.0.0.0

#include generated/pjsip.generated.conf
#include generated/pjsip.trunks.generated.conf
