[global]
type = global
user_agent = OmniPBX

[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060

[transport-tcp]
type = transport
protocol = tcp
bind = 0.0.0.0:5060

[transport-tls]
type = transport
protocol = tls
bind = 0.0.0.0:5061
cert_file = /var/lib/omnipbx/asterisk/asterisk.pem
priv_key_file = /var/lib/omnipbx/asterisk/asterisk.pem

[transport-wss]
type = transport
protocol = wss
bind = 0.0.0.0

#include generated/pjsip.generated.conf
#include generated/pjsip.trunks.generated.conf
