#!/usr/bin/env bash
set -euo pipefail

export OMNIPBX_HTTP_PORT="${OMNIPBX_HTTP_PORT:-8000}"

if command -v asterisk >/dev/null 2>&1; then
  mkdir -p \
    /etc/asterisk/generated \
    /var/log/asterisk/cdr-custom \
    /var/lib/asterisk/moh \
    /var/lib/asterisk/sounds/custom \
    /var/lib/omnipbx/asterisk \
    /var/lib/omnipbx \
    /var/lib/omnipbx/caddy \
    /var/run/asterisk \
    /var/log/asterisk \
    /var/spool/asterisk/voicemail \
    /var/spool/asterisk/monitor

  [[ -f /etc/asterisk/generated/extensions.generated.conf ]] || printf '; This file is generated by OmniPBX.\n' > /etc/asterisk/generated/extensions.generated.conf
  [[ -f /etc/asterisk/generated/pjsip.generated.conf ]] || printf '; This file is generated by OmniPBX.\n' > /etc/asterisk/generated/pjsip.generated.conf
  [[ -f /etc/asterisk/generated/pjsip.trunks.generated.conf ]] || printf '; This file is generated by OmniPBX.\n' > /etc/asterisk/generated/pjsip.trunks.generated.conf
  [[ -f /etc/asterisk/generated/extensions.trunks.generated.conf ]] || printf '; This file is generated by OmniPBX.\n[from-internal-trunks]\nexten => _X.,1,Hangup()\n' > /etc/asterisk/generated/extensions.trunks.generated.conf
  [[ -f /etc/asterisk/generated/ring_groups.generated.conf ]] || printf '; This file is generated by OmniPBX.\n[from-internal-ring-groups]\nexten => _X.,1,Hangup()\n' > /etc/asterisk/generated/ring_groups.generated.conf
  [[ -f /etc/asterisk/generated/queues.generated.conf ]] || printf '; This file is generated by OmniPBX.\n' > /etc/asterisk/generated/queues.generated.conf
  [[ -f /etc/asterisk/generated/queues_dialplan.generated.conf ]] || printf '; This file is generated by OmniPBX.\n[from-internal-queues]\nexten => _X.,1,Hangup()\n' > /etc/asterisk/generated/queues_dialplan.generated.conf
  [[ -f /etc/asterisk/generated/ivrs.generated.conf ]] || printf '; This file is generated by OmniPBX.\n[from-internal-ivrs]\nexten => _X.,1,Hangup()\n' > /etc/asterisk/generated/ivrs.generated.conf
  [[ -f /etc/asterisk/generated/musiconhold.generated.conf ]] || printf '; This file is generated by OmniPBX.\n' > /etc/asterisk/generated/musiconhold.generated.conf
  [[ -f /etc/asterisk/generated/inbound_routes.generated.conf ]] || printf '; This file is generated by OmniPBX.\n' > /etc/asterisk/generated/inbound_routes.generated.conf
  [[ -f /etc/asterisk/generated/voicemail.generated.conf ]] || printf '; This file is generated by OmniPBX.\n[general]\nformat=wav\n[default]\n' > /etc/asterisk/generated/voicemail.generated.conf

  postgres_odbc_driver="$(find /usr/lib -name 'psqlodbc*.so' -print -quit 2>/dev/null || true)"
  if [[ -z "${postgres_odbc_driver}" ]]; then
    echo "PostgreSQL ODBC driver was not found; Asterisk CDR/CEL database logging cannot start." >&2
    exit 1
  fi

  cat > /etc/odbcinst.ini <<EOF
[PostgreSQL Unicode]
Description=PostgreSQL ODBC driver
Driver=${postgres_odbc_driver}
Setup=${postgres_odbc_driver}
UsageCount=1
EOF

  cat > /etc/odbc.ini <<EOF
[OmniPBX]
Description=OmniPBX PostgreSQL
Driver=PostgreSQL Unicode
Servername=${OMNIPBX_DB_HOST:-postgres}
Port=${OMNIPBX_DB_PORT:-5432}
Database=${OMNIPBX_DB_NAME:-omnipbx}
Username=${OMNIPBX_DB_USER:-omnipbx}
Password=${OMNIPBX_DB_PASSWORD:-change-me}
ReadOnly=No
CommLog=0
EOF

  cat > /etc/asterisk/res_odbc.conf <<EOF
[omnipbx]
enabled => yes
dsn => OmniPBX
username => ${OMNIPBX_DB_USER:-omnipbx}
password => ${OMNIPBX_DB_PASSWORD:-change-me}
pre-connect => yes
sanitysql => select 1
isolation => read_committed
EOF

  cat > /etc/asterisk/manager.conf <<EOF
[general]
enabled = yes
port = ${OMNIPBX_AMI_PORT:-5038}
bindaddr = 127.0.0.1

[${OMNIPBX_AMI_USERNAME:-omnipbx}]
secret = ${OMNIPBX_AMI_PASSWORD:-change-me}
deny = 0.0.0.0/0.0.0.0
permit = 127.0.0.1/255.255.255.255
read = system,call,log,verbose,command,agent,user,config
write = system,call,command,agent,user,config,originate
EOF

  if [[ ! -f /var/lib/omnipbx/asterisk/asterisk.pem ]]; then
    openssl req -x509 -newkey rsa:2048 -nodes \
      -keyout /tmp/omnipbx-asterisk.key \
      -out /tmp/omnipbx-asterisk.crt \
      -days 3650 \
      -subj "/CN=omnipbx.local" >/dev/null 2>&1
    cat /tmp/omnipbx-asterisk.key /tmp/omnipbx-asterisk.crt > /var/lib/omnipbx/asterisk/asterisk.pem
    rm -f /tmp/omnipbx-asterisk.key /tmp/omnipbx-asterisk.crt
    chmod 600 /var/lib/omnipbx/asterisk/asterisk.pem
  fi

  if [[ ! -f /etc/asterisk/extensions.conf ]]; then
    echo "Expected Asterisk config files were not found under /etc/asterisk." >&2
    exit 1
  fi

  python3 - <<'PY'
from app.core.db import initialize_schema
from app.core.settings import get_settings
from app.services.asterisk import sync_asterisk_config
import psycopg

initialize_schema()
with psycopg.connect(get_settings().db_dsn) as connection:
    sync_asterisk_config(connection, reload_config=False)
PY

  if [[ "${OMNIPBX_START_ASTERISK:-1}" = "1" ]]; then
    asterisk -f -U root -G root &
    ASTERISK_PID=$!
  fi
fi

cleanup() {
  if [[ -n "${ASTERISK_PID:-}" ]]; then
    kill "${ASTERISK_PID}" 2>/dev/null || true
  fi
}

trap cleanup EXIT INT TERM

exec uvicorn app.main:app --host 0.0.0.0 --port "${OMNIPBX_HTTP_PORT}" --reload
