#!/usr/bin/env bash
set -euo pipefail

export OMNIPBX_HTTP_PORT="${OMNIPBX_HTTP_PORT:-8000}"

if command -v asterisk >/dev/null 2>&1; then
  mkdir -p \
    /etc/asterisk/generated \
    /var/log/asterisk/cdr-custom \
    /var/lib/asterisk/moh \
    /var/lib/asterisk/sounds/custom \
    /var/lib/omnipbx \
    /var/lib/omnipbx/caddy \
    /var/run/asterisk \
    /var/log/asterisk \
    /var/spool/asterisk/monitor

  [[ -f /etc/asterisk/generated/extensions.generated.conf ]] || printf '; This file is generated by OmniPBX.\n' > /etc/asterisk/generated/extensions.generated.conf
  [[ -f /etc/asterisk/generated/pjsip.generated.conf ]] || printf '; This file is generated by OmniPBX.\n' > /etc/asterisk/generated/pjsip.generated.conf
  [[ -f /etc/asterisk/generated/pjsip.trunks.generated.conf ]] || printf '; This file is generated by OmniPBX.\n' > /etc/asterisk/generated/pjsip.trunks.generated.conf
  [[ -f /etc/asterisk/generated/extensions.trunks.generated.conf ]] || printf '; This file is generated by OmniPBX.\n[from-internal-trunks]\nexten => _X.,1,Hangup()\n' > /etc/asterisk/generated/extensions.trunks.generated.conf
  [[ -f /etc/asterisk/generated/ring_groups.generated.conf ]] || printf '; This file is generated by OmniPBX.\n[from-internal-ring-groups]\nexten => _X.,1,Hangup()\n' > /etc/asterisk/generated/ring_groups.generated.conf
  [[ -f /etc/asterisk/generated/queues.generated.conf ]] || printf '; This file is generated by OmniPBX.\n' > /etc/asterisk/generated/queues.generated.conf
  [[ -f /etc/asterisk/generated/queues_dialplan.generated.conf ]] || printf '; This file is generated by OmniPBX.\n[from-internal-queues]\nexten => _X.,1,Hangup()\n' > /etc/asterisk/generated/queues_dialplan.generated.conf
  [[ -f /etc/asterisk/generated/ivrs.generated.conf ]] || printf '; This file is generated by OmniPBX.\n[from-internal-ivrs]\nexten => _X.,1,Hangup()\n' > /etc/asterisk/generated/ivrs.generated.conf
  [[ -f /etc/asterisk/generated/musiconhold.generated.conf ]] || printf '; This file is generated by OmniPBX.\n' > /etc/asterisk/generated/musiconhold.generated.conf
  [[ -f /etc/asterisk/generated/inbound_routes.generated.conf ]] || printf '; This file is generated by OmniPBX.\n' > /etc/asterisk/generated/inbound_routes.generated.conf

  if [[ ! -f /etc/asterisk/extensions.conf ]]; then
    echo "Expected Asterisk config files were not found under /etc/asterisk." >&2
    exit 1
  fi

  if [[ "${OMNIPBX_START_ASTERISK:-1}" = "1" ]]; then
    asterisk -f -U root -G root &
    ASTERISK_PID=$!
  fi
fi

cleanup() {
  if [[ -n "${ASTERISK_PID:-}" ]]; then
    kill "${ASTERISK_PID}" 2>/dev/null || true
  fi
}

trap cleanup EXIT INT TERM

exec uvicorn app.main:app --host 0.0.0.0 --port "${OMNIPBX_HTTP_PORT}"
